export const dummyAllMovieList = [
  {
    id: 1,
    title: "노량",
    year: 2023,
    category: "액션, 드라마",
    like: 0,
    imgUrl: "/img/노량.jpeg",
  },
  {
    id: 2,
    title: "반지의 제왕: 힘의 반지",
    year: 2022,
    category: "판타지, 모험",
    like: 0,
    imgUrl: "/img/반지의 제왕-힘의 반지.jpeg",
  },
  {
    id: 3,
    title: "인셉션",
    year: 2010,
    category: "SF, 스릴러",
    like: 0,
    imgUrl: "/img/인셉션.jpeg",
  },
  {
    id: 4,
    title: "라라랜드",
    year: 2016,
    category: "음악, 로맨스",
    like: 0,
    imgUrl: "/img/라라랜드.jpeg",
  },
  {
    id: 5,
    title: "택시 운전사",
    year: 2017,
    category: "드라마, 역사",
    like: 0,
    imgUrl: "/img/택시 운전사.jpeg",
  },
  {
    id: 6,
    title: "어벤져스: 엔드게임",
    year: 2019,
    category: "액션, SF",
    like: 0,
    imgUrl: "/img/어벤져스-엔드게임.jpeg",
  },
  {
    id: 7,
    title: "소울",
    year: 2020,
    category: "애니메이션, 가족",
    like: 0,
    imgUrl: "/img/소울.jpeg",
  },
  {
    id: 8,
    title: "모아나",
    year: 2016,
    category: "애니메이션, 모험",
    like: 0,
    imgUrl: "/img/모아나.jpeg",
  },
  {
    id: 9,
    title: "기생충",
    year: 2019,
    category: "드라마, 스릴러",
    like: 0,
    imgUrl: "/img/기생충.jpeg",
  },
  {
    id: 10,
    title: "매트릭스",
    year: 1999,
    category: "액션, SF",
    like: 0,
    imgUrl: "/img/매트릭스.jpeg",
  },
];
